### ISSUE TITLE
Return de condition

### ISSUE THREAD

**Issue by DaanKorver** [TristanVarewijck/TechDefined#4]
https://github.com/TristanVarewijck/TechDefined/blob/e75b8e655aeb1378c9cf0a3c92fb7ceb41fe4465/scripts/articleAnimation.js#L7-L11

Dit kan makkelijker doen door direct de condition die je checkt in de if statement te returnen.

**Comment by TristanVarewijck** [comment]
Bedankt voor de feedback ) - Ik gebruik de articleAnimation.js niet meer opgelost met "intersectionObserver"
