### ISSUE TITLE
Verschil tussen articleAnimation.js & articleObserver.js?

### ISSUE THREAD

**Issue by DaanKetelaars** [TristanVarewijck/TechDefined#7]
Wat is precies het verschil tussen die 2 bestanden? Als ze hetzelfde doen kan er sowieso 1 weg, als ze samen werken kun je het misschien ook koppelen om er 1 bestand van te maken?

**Comment by TristanVarewijck** [comment]
1 van de bestanden is overbodig, ik zal dit in de .env zetten mischien wil ik het later ooit nog gebruiken :)
